"""Report Generator — produces markdown + PDF compliance audit reports."""
from __future__ import annotations

import io
from datetime import datetime, timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)
from reportlab.lib import colors


SEVERITY_COLORS = {
    "CRITICAL": "#DC2626",
    "HIGH": "#EA580C",
    "MEDIUM": "#D97706",
    "LOW": "#65A30D",
    "OK": "#16A34A",
    "COMPLIANT": "#16A34A",
    "NON_COMPLIANT": "#DC2626",
}


class ReportGenerator:
    """Generates both markdown and PDF reports from audit results."""

    def to_markdown(self, results: dict) -> str:
        cfg = results["config"]
        summary = results["summary"]
        lines = []
        lines.append(f"# LUMIS AI Bias Audit Report")
        lines.append("")
        lines.append(f"**Audit ID:** `{results['audit_id']}`")
        lines.append(f"**Domain:** {cfg['domain'].title()}")
        lines.append(f"**Model Endpoint:** `{cfg.get('model_endpoint', 'N/A')}`")
        lines.append(f"**Sample Size:** {results['execution']['profiles_generated']:,} synthetic profiles")
        lines.append(f"**Generated:** {results['completed_at']}")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"- **Risk Level:** {summary['risk_level']}")
        lines.append(f"- **Fairness Score:** {summary['fairness_score']} / 1.000")
        lines.append(f"- **Metrics Failed:** {summary['metrics_failed']} / {summary['total_metrics_evaluated']}")
        lines.append(f"- **Critical Findings:** {summary['critical_findings']}")
        lines.append(f"- **High-Severity Findings:** {summary['high_findings']}")
        lines.append(f"- **Proxy Features Detected:** {summary['proxies_detected']}")
        lines.append("")

        lines.append("## Compliance Status")
        lines.append("")
        for fw_key, fw_result in results.get("compliance", {}).items():
            status_emoji = "PASS" if fw_result["status"] == "COMPLIANT" else "FAIL"
            lines.append(f"### {fw_result['framework']}")
            lines.append(f"**Status:** {status_emoji} — `{fw_result['status']}`")
            if fw_result["failed_metrics"]:
                lines.append("")
                lines.append("**Failed metrics:**")
                for fm in fw_result["failed_metrics"]:
                    lines.append(f"- `{fm['metric']}` on `{fm['attribute']}` (value: {fm['value']})")
            lines.append("")

        lines.append("## Detailed Findings")
        lines.append("")
        for attr, metrics in results["metrics"].items():
            lines.append(f"### Protected Attribute: `{attr}`")
            lines.append("")
            lines.append("| Metric | Value | Threshold | Status | Severity |")
            lines.append("|---|---|---|---|---|")
            for m in metrics:
                status = "PASS" if m["passed"] else "FAIL"
                lines.append(f"| {m['metric']} | {m['value']} | {m['threshold']} | {status} | {m['severity']} |")
            lines.append("")
            for m in metrics:
                lines.append(f"- **{m['metric']}**: {m['interpretation']}")
            lines.append("")

        if results.get("intersectional"):
            inter = results["intersectional"]
            if inter:
                lines.append("## Intersectional Analysis")
                lines.append("")
                lines.append(inter.get("interpretation", ""))
                lines.append("")

        proxy = results.get("proxy_detection", {})
        if proxy.get("proxies_detected", 0) > 0:
            lines.append("## Proxy Feature Detection")
            lines.append("")
            for p in proxy["details"]:
                lines.append(f"- **{p['feature']}** correlates {p['correlation']} with `{p['proxy_for']}` — {p['interpretation']}")
            lines.append("")

        lines.append("## Recommendations")
        lines.append("")
        for i, rec in enumerate(results.get("recommendations", []), 1):
            lines.append(f"### {i}. [{rec['priority']}] {rec['title']}")
            for action in rec["actions"]:
                lines.append(f"- {action}")
            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by LUMIS — Large Unified Model Inspection System*")
        lines.append("*Powered by MiroFish synthetic-population simulation*")
        return "\n".join(lines)

    def to_pdf(self, results: dict) -> bytes:
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=letter,
            leftMargin=0.75 * inch, rightMargin=0.75 * inch,
            topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        )
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "title", parent=styles["Heading1"], fontSize=22,
            textColor=HexColor("#0F172A"), spaceAfter=12, alignment=0,
        )
        h2_style = ParagraphStyle(
            "h2", parent=styles["Heading2"], fontSize=15,
            textColor=HexColor("#1E40AF"), spaceAfter=8, spaceBefore=14,
        )
        body = styles["BodyText"]
        story = []

        story.append(Paragraph("LUMIS AI Bias Audit Report", title_style))
        cfg = results["config"]
        meta_data = [
            ["Audit ID", results["audit_id"]],
            ["Domain", cfg["domain"].title()],
            ["Model Endpoint", cfg.get("model_endpoint", "N/A")],
            ["Sample Size", f"{results['execution']['profiles_generated']:,}"],
            ["Completed", results["completed_at"]],
        ]
        t = Table(meta_data, colWidths=[1.5 * inch, 5 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), HexColor("#F1F5F9")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.2 * inch))

        summary = results["summary"]
        story.append(Paragraph("Executive Summary", h2_style))
        risk_color = SEVERITY_COLORS.get(summary["risk_level"], "#64748B")
        story.append(Paragraph(
            f'<b>Risk Level:</b> <font color="{risk_color}">{summary["risk_level"]}</font>',
            body
        ))
        story.append(Paragraph(f"<b>Fairness Score:</b> {summary['fairness_score']} / 1.000", body))
        story.append(Paragraph(
            f"<b>Metrics Failed:</b> {summary['metrics_failed']} / {summary['total_metrics_evaluated']}",
            body
        ))
        story.append(Paragraph(f"<b>Critical Findings:</b> {summary['critical_findings']}", body))
        story.append(Paragraph(f"<b>High-Severity Findings:</b> {summary['high_findings']}", body))
        story.append(Paragraph(f"<b>Proxy Features Detected:</b> {summary['proxies_detected']}", body))

        story.append(Paragraph("Compliance Status", h2_style))
        for fw_key, fw_result in results.get("compliance", {}).items():
            status_color = SEVERITY_COLORS.get(fw_result["status"], "#64748B")
            story.append(Paragraph(
                f'<b>{fw_result["framework"]}:</b> '
                f'<font color="{status_color}"><b>{fw_result["status"]}</b></font>',
                body
            ))
            if fw_result["failed_metrics"]:
                for fm in fw_result["failed_metrics"]:
                    story.append(Paragraph(
                        f"&nbsp;&nbsp;&bull; <font color='#DC2626'>FAIL</font> "
                        f"<i>{fm['metric']}</i> on <i>{fm['attribute']}</i>: {fm['value']}",
                        body
                    ))
        story.append(Spacer(1, 0.1 * inch))

        story.append(Paragraph("Detailed Findings by Protected Attribute", h2_style))
        for attr, metrics in results["metrics"].items():
            story.append(Paragraph(f"<b>{attr.title()}</b>", styles["Heading3"]))
            data = [["Metric", "Value", "Threshold", "Status", "Severity"]]
            for m in metrics:
                status = "PASS" if m["passed"] else "FAIL"
                data.append([
                    m["metric"].replace("_", " ").title(),
                    str(m["value"]),
                    str(m["threshold"]),
                    status,
                    m["severity"],
                ])
            tbl = Table(data, colWidths=[2.2 * inch, 0.9 * inch, 0.9 * inch, 0.8 * inch, 1 * inch])
            style_cmds = [
                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1E40AF")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#CBD5E1")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("PADDING", (0, 0), (-1, -1), 4),
            ]
            for i, m in enumerate(metrics, 1):
                if not m["passed"]:
                    style_cmds.append(("TEXTCOLOR", (3, i), (3, i), HexColor("#DC2626")))
                style_cmds.append((
                    "TEXTCOLOR", (4, i), (4, i),
                    HexColor(SEVERITY_COLORS.get(m["severity"], "#64748B"))
                ))
            tbl.setStyle(TableStyle(style_cmds))
            story.append(tbl)
            story.append(Spacer(1, 0.05 * inch))
            for m in metrics:
                story.append(Paragraph(f"<i>{m['metric']}:</i> {m['interpretation']}", body))
            story.append(Spacer(1, 0.1 * inch))

        proxy = results.get("proxy_detection", {})
        if proxy.get("proxies_detected", 0) > 0:
            story.append(PageBreak())
            story.append(Paragraph("Proxy Feature Detection", h2_style))
            for p in proxy["details"]:
                story.append(Paragraph(
                    f"<b>{p['feature']}</b> correlates {p['correlation']} with <i>{p['proxy_for']}</i>: "
                    f"{p['interpretation']}",
                    body
                ))

        recs = results.get("recommendations", [])
        if recs:
            story.append(PageBreak())
            story.append(Paragraph("Recommendations", h2_style))
            for i, rec in enumerate(recs, 1):
                p_color = SEVERITY_COLORS.get(rec["priority"], "#64748B")
                story.append(Paragraph(
                    f'{i}. <font color="{p_color}"><b>[{rec["priority"]}]</b></font> '
                    f'<b>{rec["title"]}</b>',
                    body
                ))
                for action in rec["actions"]:
                    story.append(Paragraph(f"&nbsp;&nbsp;&bull; {action}", body))
                story.append(Spacer(1, 0.08 * inch))

        story.append(Spacer(1, 0.3 * inch))
        story.append(Paragraph(
            "<i>Generated by LUMIS — Large Unified Model Inspection System.<br/>"
            "Powered by MiroFish synthetic-population simulation engine.</i>",
            body
        ))

        doc.build(story)
        buf.seek(0)
        return buf.read()
